### PR TITLE
Add Dark Reading, The Canberra Times

### PR DESCRIPTION
**Pull request by iscreamcoke**
Add darkreading.com, canberratimes.com.au

Request #367

### CODE REVIEW

**Comment by magnolia1234** [comment]
You could use a for-loop (or forEach) to remove class for all selected DomElements (not only first -> [0]).

**Comment by iscreamcoke** [comment]
That's what I did in the first place but I surely did a mistake as it didn't work:

`if (window.location.href.indexOf("canberratimes.com.au") !== -1) {
    
        const paywall = document.querySelector('.subscribe-article.news-article-body.article__body');
        paywall.classList.remove('subscribe-article');
	
	var content = document.getElementsByClassName('subscriber-hider')[0];
        var i = 0;

        for (var i = content; i++;) {
        content[i].classList.remove('subscriber-hider');
    }
}`

**Comment by iscreamcoke** [comment]
That's what I did in the first place but I surely made a mistake as it didn't work:
```
if (window.location.href.indexOf("canberratimes.com.au") !== -1) {
    
        const paywall = document.querySelector('.subscribe-article.news-article-body.article__body');
        paywall.classList.remove('subscribe-article');
    
        var content = document.getElementsByClassName('subscriber-hider')[0];

        for (var i = 0; i < content.length; i++) {
        content[i].classList.remove('subscriber-hider');
    }
}
```

**Comment by magnolia1234** [comment]
You only select the first element in content.
Remove the [0].

**Comment by iscreamcoke** [comment]
Haha, that's something I should have seen. Works like a charm now. Thanks!

**Comment by magnolia1234** [comment]
How come twice if-canberra (intermediate change not visible in commits)?

**Comment by iscreamcoke** [comment]
That was a glitch. Forgot to remove the old condition

**Comment by iscreamcoke** [comment]
That's weird because I did the same thing for Le Parisien, but it only works when I right click > inspect on Chrome, with no further intervention needed (the style is indeed removed in the code).

**Comment by magnolia1234** [comment]
Almost there ;-)

Canberra Times
- regular articles (monthly limit of 5), could you add cookie-settings (both allow_cookies & remove_cookies)?
- subscriber articles, remove div (above comments) with class 'subscriber-container'

Le Parisien:
- add site to title/description of PR 
- subscriber article still blurred while scrolling: remove newsletter overlay, class 'margin_bottom_md'

**Comment by iscreamcoke** [comment]
Thanks for the feedback!

* Canberra Times: done/done
* Le Parisien: removed newsletter, but content still blurred while the style is removed. Only becomes readable when I inspect the element for no apparent reason.

**Comment by magnolia1234** [comment]
Indeed, but I can block the blurring by using uMatrix or uBlock Origing (blocking base.js) ...

**Comment by iscreamcoke** [comment]
Well I couldn't find a workaround for Le Parisien, so I deprecated the partial support for the moment, kept the code on a side, and proposed the PR to the main repo

**Pull request closed without merging**
