### PR TITLE
Add Scribd & Remove The Times subscription block

### PR DESCRIPTION
**Pull request by iscreamcoke**
* Scribd support (unblur text)
* Remove subscription block for The Times
* Fanboy's Enhanced Trackers List in readme

### CODE REVIEW

**Comment by magnolia1234** [comment]
Scribd
* remove div's with class between_page_portal_root visible
* remove div's with class between_page_module visible
* remove div (at the bottom) with class auto__doc_page_webpack_doc_page_body_static_promo_study
* promo-div is no longer visible after removing blurred_page though

**Comment by magnolia1234** [comment]
also div's with class auto__explain_scribd_v2_advertisement

**Comment by magnolia1234** [comment]
Scribd
* promo & ad css-selector .classname are not correct
* if-check for removeDOMElement not necessary
Times.co.uk
* css-selector .subscription-block is sufficient

**Comment by iscreamcoke** [comment]
corrected, thanks

**Comment by iscreamcoke** [comment]
The Times doesn't work with `const block = document.querySelector('.subscription-block');` though

**Comment by magnolia1234** [comment]
Not yet, ad-class should be .auto__explain_scribd_v2_advertisement (copy typo?)
And shorter like removeDOMElement(portal, page_module, promo, ad);

**Comment by magnolia1234** [comment]
Times.co.uk working just fine with .subscription-block
Also blocked by uBlock Origin for me though.

**Comment by magnolia1234** [comment]
Btw Scribd-fix only active on documents (maybe add description to options.js).

**Comment by iscreamcoke** [comment]
Fixed, ready for merging.

**Comment by magnolia1234** [comment]
New commit: Bugfix contentScript.js (restore var instead of let)
Did you actually test your last version?
PS still missing Appendix I in the test-document, but now working with Scribd-trial ...
https://www.scribd.com/document/326139414/Diplomacy-for-the-21st-Century-Embedding-a-Culture-of-Science-and-Technology-Throughout-the-Department-of-State#logout

**Comment by iscreamcoke** [comment]
I'm sorry for that...

**Comment by magnolia1234** [comment]
No worries, but test and also check Console-log for errors.
PS Appendix I looks like timing issue of Scribd (large images in pdf).
Now working while logged in (yesterday not).

**Comment by iscreamcoke** [comment]
Great!
PS: what websites do you want to add to custom for now?

**Comment by magnolia1234** [comment]
We could actually add all sites to 'custom' list, but then we have to empty allow/remove_cookies arrays from background.js (plus add drop-specific-fake-cookie for sites who can hold on to cookies).
defaultSites are objects, so no problem with double entries (overwritten).
So a major/minor division in options would still be possible (major list in defaultSites of options.js and others from custom list).

**Comment by iscreamcoke** [comment]
Ok so lets do that!
Ps: we have some other issue. I'm hitting the paywall on the[ MIT Tech Review](https://www.technologyreview.com/) after 3 articles viewed. The bypass can actually be bypassed by disabling javascript so there's a workaround.

Screenshot 2019-12-29 at 22 11 48

**Comment by magnolia1234** [comment]
You actually did it, crashed GitHub's comment system ;-)
I got a notification about your MIT Tech Review issue, but no message here.
Btw the site is working fine (also with uBlock Origin disabled), just banner and click read-more-button.

**Comment by iscreamcoke** [comment]
;-) I actually wanted to automatically click the button 'Read the whole story' on the MIT Tech Review when we reach 3 articles.
https://www.technologyreview.com/s/614934/teenagers-without-cell-phones/

My code doesn't have any effect:
```
if (window.location.href.indexOf("technologyreview.com") !== -1) {
    const read_story = document.querySelector('.storyExpanderButton');
        if (read_story)
            read_story.click();
    document.getElementsByClassName('close-icon').click();
}
```

**Comment by iscreamcoke** [comment]
Screenshot 2019-12-29 at 22 33 50
her and there

**Comment by magnolia1234** [comment]
MIT-fix working just fine for me though.
You haven't included my let-bugfix, I guess (corrupts contentScript.js) ...

**Comment by iscreamcoke** [comment]
You're right, I submit a PR

**Comment by magnolia1234** [comment]
PS you actually never reach 3-article-limit becayse of cookie-fix.
Could you also add if-check for close-icon?

**Pull request merged**
