### PR TITLE
Add The Real Deal to custom & sticky banners

### PR DESCRIPTION
**Pull request by iscreamcoke**
Add therealdeal.com (NYC real estate) in custom list, as requested in PR [#388](https://github.com/iamadamdev/bypass-paywalls-chrome/pull/388)

### CODE REVIEW

**Comment by iscreamcoke** [comment]
btw the extension doesn't work on The Atlantic @magnolia1234 

Screenshot 2020-01-01 at 22 35 17

**Comment by magnolia1234** [comment]
The Atlantic is working just fine for me though (also without adblocker).
PS BP doesn't have to block every banner whcih can be blocked by an adblocker ...

**Comment by iscreamcoke** [comment]
ok but block at least those of the washington post, they're horrible

**Comment by magnolia1234** [comment]
Have you fixed The Atlantic (cookie-fix not active)?
I don't get WaPo's element_id's i_userMessages & wallIframe (Mac specific?).

**Comment by iscreamcoke** [comment]
No. The new extension is still causing cookie issues for me (github, google), cookie-loop on the washington post, and apparently cookie issue on the atlantic (still unresolved). Maybe mac-related

**Comment by iscreamcoke** [comment]
I confirm that The Atlantic issue (and other cookie issues) is resolved by using the version on Adam's repo

btw I'm just blocking paywall-related banners/popups, for the user to have a subscriber-like experience. nothing else

**Comment by magnolia1234** [comment]
Which new extension, v1.6.1+?
You didn't tamper with background.js (check Chrome DevTools console)?
You're on your own now (with Mac) ;-)

**Comment by magnolia1234** [comment]
PS your fork is also working just fine for me.
Maybe you're having a conflict with another extension?

**Comment by iscreamcoke** [comment]
I wanted to answer here in the first place. I'll keep you up to date if I find answers related to Chrome cookies on MacOS

**Comment by magnolia1234** [comment]
Check Chrome DevTools ...

**Comment by magnolia1234** [comment]
PS just had similar cookie-issues with Android Chrome (no extensions), but caused by AdGuard-app.
I guess they messed up some adblock cookie-filter (just updated, no fix yet but to disable AdGuard).

**Comment by magnolia1234** [comment]
I had to disable Stealth Mode (anti-tracking) in AdGuard.

**Comment by iscreamcoke** [comment]
Ok so I have the beginning of an answer. When installing the extension, it will log me out from all sites until I click 'save' in the window of installation. If I don't click it, it will keep me logged out until I save in BP (no need to check/uncheck/save as I told you before).

That said, it doesn't solve The Atlantic cookie issue.

**Comment by iscreamcoke** [comment]
I have no other active extension, no proxy, no other firewall than the basic MacOS one, I removed OpenDNS, tried on different wifis, on different browser, etc. It doesn't change anything.

**Comment by iscreamcoke** [comment]
The Atlantic indeed works if I refresh the BP from the Chrome extensions page, although the cookie popup appears on each page now...

I think we need someone with a Mac to test if it's just me or some bug related to the OS.

**Comment by magnolia1234** [comment]
Fix The Atlantic (cookie notice).
For those who don't use an adblocker with Easylist Cookie-filter or 'I don't care about cookies'-extension ;-)

**Comment by iscreamcoke** [comment]
Thanks, but I already used "I don't care about cookies". Your fix hasn't solved the cookie-counter on The Atlantic or the cookie-loops on other sites (e.g. the washpost) unfortunately :'-(

**Pull request closed without merging**
