### PR TITLE
[Quick Fix] Style consistency in readme.md & styling in background.js

### PR DESCRIPTION
**Pull request by iscreamcoke**
A quick styling fix

### CODE REVIEW

**Comment by magnolia1234** [comment]
Not family of Mr JsLint cimke? ;-)

**Comment by iscreamcoke** [comment]
What are your views regarding Adam's repeated and lasting absences?

**Comment by magnolia1234** [comment]
Well, obviously the response speed is too slow ...
And I'm not sure if he's got the time, will and/or knowledge to develop the extension any further (lots of bugs repaired sofar).
I've been thinking already to clone this fork to a main (new) extension on GitHub.

**Comment by iscreamcoke** [comment]
I think the best solution would be to ask him to add you as a maintainer of his repo when he comes back. I think he trusts you now, since you've been committing PRs since a couple of months now

**Comment by iscreamcoke** [comment]
The best solution would be to ask him to add you as a maintainer of his repo when he comes back, in order to keep the audience. I think he trusts you now, you've been committing PRs since a couple of months now

**Comment by iscreamcoke** [comment]
Unless you have a bigger project in mind

**Comment by magnolia1234** [comment]
Whatever it takes to speed up the releases. I can sign my own crx/xpi-files, but they won't udate to those of Adam. Maybe a Google Analytics-free alternative.

**Pull request closed without merging**
