### PR TITLE
Refresh the current tab after options.js is saved & Installation instructions for Yandex browser on Android & Table of contents in readme.md

### PR DESCRIPTION
**Pull request by iscreamcoke**
I have started an alternative PR to rather focus on helpful, simple and quick improvements:

> Refresh the current tab after options.js is saved
> Installation instructions for Yandex browser on Android
> Table of contents in readme.md

### CODE REVIEW

**Comment by magnolia1234** [comment]
Busy again ;-)
Btw all install instruction points have 1. (autocorrect?).

**Comment by iscreamcoke** [comment]
the glitch was already in the original .md file, I've corrected it ;-)

**Comment by magnolia1234** [comment]
Really? Current Readme.md has 1 until 5 though.

**Comment by iscreamcoke** [comment]
Screenshot 2019-12-27 at 19 27 59

No I'm sure. Look, this is a screenshot from magnolia/bypass/readme.md

**Comment by iscreamcoke** [comment]
Markdown accepts both formats indeed. This is just for code style

**Comment by magnolia1234** [comment]
Yes, Github's edit-mode is messed up.

**Comment by iscreamcoke** [comment]
Btw Magnolia, since blocking paywall services like `assets.poool.fr` brings collateral issues to other websites, could you just help me add the support of challenges.fr or valeursactuelles.com to the extension, as it was request in issues.

I've tried to block the regex in background.js with no result...

**Comment by iscreamcoke** [comment]
Btw Magnolia, since doing a global blocking of paywall services like `assets.poool.fr` in uBlock brings collateral issues to other websites, could you just help me add the support of challenges.fr or valeursactuelles.com to the extension, as it was requested in issues.

I've tried to block the regex in background.js with no result...

Samples of premium articles for [Challenges](https://www.challenges.fr/automobile/actu-auto/tesla-numero-un-des-des-vehicules-electrifies-devant-bmw-et-renault_691349) and [Valeurs Actuelles](https://www.valeursactuelles.com/clubvaleurs/culture/j-r-r-tolkien-le-forgeur-de-mythes-114366)

**Comment by magnolia1234** [comment]
Mix-up of issues?

**Comment by iscreamcoke** [comment]
Yes sorry, I've have just cloned it to the original thread in case other devs wants to get involved

**Comment by magnolia1234** [comment]
Scribd fix not working?

**Comment by iscreamcoke** [comment]
no, I was trying to import this [MIT-licensed extension](https://github.com/kush789/Unblur-Scribd/tree/master/Chrome_extension). But eventually it did'nt work because of jquery. It's too bad, Scribd would have been a great feature.

**Comment by magnolia1234** [comment]
Can't you convert the script to regular Javascript? UnblurDoc is recursive though (with timeout of a second).

**Comment by iscreamcoke** [comment]
What I have done so far (partially working):

`if (window.location.href.indexOf("scribd.com") !== -1) {

function unblurDoc() {
    const paywall = document.querySelector('.autogen_class_views_read2_page_blur_promo');
    removeDOMElement(paywall);

    const promo = document.querySelector('.promo');
    removeDOMElement(promo);

    const page_blur_promo_overlay = document.querySelector('.page_blur_promo_overlay');
    removeDOMElement(page_blur_promo_overlay);

    const between_page_ads = document.querySelector('.between_page_ads');
    removeDOMElement(between_page_ads);

    var text_layer = document.querySelectorAll('.text_layer');
    var absimg = document.querySelectorAll('.absimg');

    text_layer.style.color = "#000";
    absimg.style.opacity = "1.0";
    text_layer.style.text-shadow = "black 0px 0px 0px";

    const page_blur_promo = document.querySelector('.page_blur_promo');
    removeDOMElement(page_blur_promo);

    setTimeout(unblurDoc, 1000);
};

unblurDoc()

}`

**Comment by iscreamcoke** [comment]
Compare to original JQuery:

```
function unblurDoc() {

    $('.autogen_class_views_read2_page_blur_promo').remove();

    $('.promo').remove();   
    $('.page_blur_promo_overlay').remove();

    // $('.page_blur_promo').remove();
    // $('.page_blur_promo_overlay').remove();

    $('.between_page_ads').remove();

    $('.text_layer').css('color', '#000');
    $('.absimg').css('opacity', '1.0');
    $('.text_layer').css('text-shadow','black 0px 0px 0px');
    $('.page_blur_promo').remove(); // Removes pesky ads.
    
    setTimeout(unblurDoc, 1000);
};

unblurDoc()
```

**Comment by magnolia1234** [comment]
Do you actually have an example of this Scribd blurring?

**Comment by magnolia1234** [comment]
Not working on https://www.scribd.com/document/136858179/Foreign-Affairs-Handbook-01-0120-89322

**Comment by magnolia1234** [comment]
Bugfixes
some classnames have changed (like page_blur_promo etc.).
querySelectorAll selects mutiple elements, so handle them all.
text_layer.style.text-shadow has to be text_layer.style.textShadow

After some editing I've got it working on this 191-page article:
https://www.scribd.com/document/326139414/Diplomacy-for-the-21st-Century-Embedding-a-Culture-of-Science-and-Technology-Throughout-the-Department-of-State

**Comment by iscreamcoke** [comment]
Yes, the code had changed since the release of the extension. I think you can do something similar by setting all booleans pageParams.blur to 'false' inside <script type='text/javascript'></script>

**Comment by iscreamcoke** [comment]
Yes the method above works to unblur the text. You just have to apply the cosmetic filters (opacity, shadow) and remove the popup 'promo'

**Comment by magnolia1234** [comment]
'Just' fix your code then ;-)

**Comment by iscreamcoke** [comment]
Working on it. I'm contributing to this project to improve my limited JS knowledge, so thank you for helping me! My real job is to give advice to companies on their digital marketing strategies, not to write code ;-)

**Comment by magnolia1234** [comment]
Btw pages with appendix I are missing (p.162/3) ...

**Comment by iscreamcoke** [comment]
yes sorry I hadn't seen it. Done

**Comment by iscreamcoke** [comment]
Added: hyperlink to uBlock Origin's webstore page, to avoid confusion with unrelated [eponymous extension](https://chrome.google.com/webstore/detail/ublock-free-ad-blocker/epcnnfbjfcgphgdmggkamkmgojdagdnn?hl=en)

**Pull request merged**
