### PR TITLE
Remove subscription banners + readme update

### PR DESCRIPTION
**Pull request by iscreamcoke**
* Remove sticky subscription/page counter banners on Bloomberg, Asia Nikkei & Haaretz.com. I know they can be blocked by uBlock, but are annoying to users and stick to each page they visit, sometimes taking one third of the screen.
* Add 'don't remove the extension's folder after installation' in readme.md
* Deprecate Dynamed
* dn.se (free articles only)

### CODE REVIEW

**Comment by magnolia1234** [comment]
Have you checked all the sites in BP yet? ;-)
Btw if-check for removeDOMElement is redundant.

**Comment by iscreamcoke** [comment]
yes they work I've tested ;)

**Comment by magnolia1234** [comment]
Could you add the removal of the Bloomberg-banner to the other Bloomberg-script though?

**Comment by iscreamcoke** [comment]
merged, tested and working!

**Pull request merged**
