### PR TITLE
Updating custom list

### PR DESCRIPTION
**Pull request by iscreamcoke**
* moved sites to list of custom sites (La Nacion, Loeb Classical, Irish Times)

### CODE REVIEW

**Comment by magnolia1234** [comment]
Maybe also edit Readme.md or new custom sites section.

**Comment by iscreamcoke** [comment]
I don't know how Adam want to organise the readme, especially regarding his other extension.
This is a first update

**Comment by iscreamcoke** [comment]
Maybe you should rename the custom list in sites_custom.json with a more straightforward title and a description:

```
  "----- Soft-paywalled sites -----": "",
  "Selected sites will have their cookies cleared and blocked.": "",
```

**Comment by magnolia1234** [comment]
Or include a weblink to the json-file for the latest version.

**Comment by magnolia1234** [comment]
PS interesting, GitHub has a new bug: I could edit your comment (see dot) ;-)

**Comment by iscreamcoke** [comment]
Yes that's because you're the owner of the repo ;)

**Comment by iscreamcoke** [comment]
I always think 'what is easier to use for the average user?' 95% of them won't submit a PR but rather an issue requesting the support of their soft-paywalled website, as it's the case today. But if you think blob is better, I'll restore it.

For the user-side title of the custom list, we can alternatively re-use the one from readme.md ('Sites with limited number of free articles'), it'll be more straightforward for users

**Comment by magnolia1234** [comment]
Raw version looks better, but then you leave GitHub context.

**Comment by iscreamcoke** [comment]
I have moved all websites that relied on a soft paywall/cookie counter towards sites_custom.json

**Comment by magnolia1234** [comment]
You've been busy ;-)
Btw for me the custom list is not for all sites with free-article-limit, but primarily for less known (minor) sites.

**Comment by magnolia1234** [comment]
PS these sites actually have a metered paywall instead of soft paywall (hiding content).

**Comment by iscreamcoke** [comment]
I mean, "custom sites" will appear in options anyway, and the line between "major" and "minor" sites is sometimes hard to draw. I thought the intent was the make the maintenance of the list easier by allowing for the inclusion of metered-paywalled papers to the extension with only one line of code.

**Comment by magnolia1234** [comment]
No worries.
PS your latest commit is loading local json-file again (test-modus).
You can combine first 2 lines of sites_custom.json into one with a break-element <br>

**Comment by iscreamcoke** [comment]
Works without a break-element, the window size is fixed

**Comment by magnolia1234** [comment]
Merge issues in Readme.md after merging PR #15

**Comment by magnolia1234** [comment]
PS also sites with just default cookie-blocking (not in allow/remove_cookies) can indeed be moved to sites_custom.js list, but also sites with specific cookie hold/drop or in Googlebot/contentScript.js list.
Still waiting for @iamadamdev to merge custom list though ...

**Comment by iscreamcoke** [comment]
If any site of the extension can be added to the .json file, then we could load the entire list in option remotetly. I can't really see the distinction you want to want between 'general' and 'custom' (popularity, metered paywall, possibly all sites?)

**Comment by magnolia1234** [comment]
Customs sites were meant to bypass Adam's reluctance to add new/minor sites.
His only response sofar was to add an UI to add custom sites, but it's still my intension to keep a central list of websites.
It major/minor subdivision would be usefull to keep all sites in Readme.md though.
PS also configuration settings (like Googlebot etc.) could be incorporated in sites_custom.js.

**Comment by iscreamcoke** [comment]
35 sites are curently only loaded in the default list to block cookies.

Personnally, I think the smoothest way to deal with metered paywall is to add a button to block cookies for the current url. While Adam's other extension is good to empty stored cookies, it doesn't feature the option to definetly block cookies for the url like [this extension](https://github.com/SingleClickApps/disable-cookies).

**Comment by magnolia1234** [comment]
Possible, but it would require an extra list of really custom sites in the local storage (with option to export or transfer list?).
A general (easy to maintain) list would be more userfriendly.
Btw all sites with no allow/remove_cookies setting can also be added to custom sites.

**Comment by iscreamcoke** [comment]
You're right for the common list. What do you propose for the custom list? That we add all metered paywalls in sites_customs.json as I did in this PR?

**Comment by magnolia1234** [comment]
All sites in sites_custom.js list with extra settings in background.js & major/minor subdivision in readme.md.
If cookies are allowed we can drop a fake cookie (and hold the rest).
No more defaultSites lists needed (or synching) because all sites are default anyway (read from list).

**Comment by iscreamcoke** [comment]
I've tested to load all sites from local .json file, and all of them seems to work fine. No need for a double list in background.js and option.js

**Comment by magnolia1234** [comment]
Nice, but just keep in mind the cookie-settings for sites which can hold on to their cookies (like nytimes.com & volkskrant.nl).
Btw top50-list of Newspapers:
https://www.alexa.com/topsites/category/Top/News/Newspapers

**Comment by iscreamcoke** [comment]
Good list, but would you restrict major sites to a top 50 of visits? The Alexa list doesn't include the Wall Street Journal or the Financial Times for instance. Newspapers are often rather ranked by their number of citations in other publications, breaking news revealed and prizes earned (Pulitzer, etc.)

**Comment by iscreamcoke** [comment]
Btw, I have an issue when I use the extension, it sometimes restricts me from logging to GitHub or Google, probably due to a cookie setting. I have reinstalled it from fresh from your repo, with the same issue. Haven't tried with Adam's version.

**Comment by magnolia1234** [comment]
Well, we don't have to select the Nobel prize for news sites ;-)
Maybe arbitrary selection, but we have to start somewhere.
Btw wsj.com is 21st in news ranking:
https://www.alexa.com/topsites/category/Top/News

BP has no effect on Github or Google cookies, but I've disabled uBlock Origin for Github.

**Comment by iscreamcoke** [comment]
Concerning the paywall services, Fanboy's Enhanced Tracking List already includes most of them; and I have asked them to add `assets.poool.fr`.

What do you think of advising user in the readme to subscribe to the list in uBlock?

**Comment by magnolia1234** [comment]
Yes, lots of usefull filters are not enabled by default.
PS any progress with Scribd-documents unblurring?

**Comment by iscreamcoke** [comment]
See PR #17

**Pull request closed without merging**
